### ISSUE TITLE
Crash on selecting settings from the navigation menu

### ISSUE THREAD

**Issue by SalmanTKhan** [vpaliyX/PopularMovies#2]
No "com.popularmovies.vpaliy.popularmoviesapp.ui.details.fragment.SettingsFragment" found

Thanks for such a complete project, taking it apart to help my understanding of clean architecture.

**Comment by vpaliyX** [comment]
I'm not sure why are you getting this error. It seems like there is a reference to this fragment(which was deleted long ago) in the code you've downloaded. Can you share with more details, maybe a snapshot?

Thank you, it's not complete though. Only the first part is done, I want to implement more features in the future, so stay tuned:)

**Comment by SalmanTKhan** [comment]
So it's referenced in the activity_settings.xml, I just ended up deleting the fragment reference in the layout file.

https://github.com/vpaliyX/PopularMovies/blob/master/presentation/src/main/res/layout/activity_settings.xml

**Comment by vpaliyX** [comment]
I apologize, might have accidentally deleted the file. Check my last commit, now it's in the settings package.

**Comment by vpaliyX** [comment]
I suppose, the problem has been resolved, so I'm closing the issue.
